### ISSUE TITLE
Labeling in main siren settings menu not ordered correctly.

### ISSUE THREAD

**Issue by Salzian** [TrevorBarns/luxart-vehicle-control#8] opened 2020-10-04 15:34 UTC
In VEHICLES.lua I added a custom car like this:

`car = { 1, 7, 10, 4 }`

My intention is to have the cycle in the order of 7, 10, 4. Using `R` to cycle those does work as expected and retains the order.

Now have a look at this list.

![2020-10-04 17_28_11-FiveM - Salzian Local Dev](https://user-images.githubusercontent.com/23481219/95019689-2067be00-0667-11eb-912f-76a72f8ed451.png)

The labels are instead ordered by the corresponding number of the sound.

Priority = 4
BikeWail = 7
BikeYelp = 10

While this may be confusing on it's own, the real problem is, that the settings on the right (_Cycle & Button_) does **not** follow this ordering. To set the Priority sound to e.g. _"Cycle only"_, you need to set _BikeYelp_ at the bottom.

**Comment by TrevorBarns** [comment] 2020-12-26 21:10
This behavior is not currently supported, LVC was designed with tone IDs being in numerical order. The reason being is if you wanted to change the siren tone order, you could change the tone wav files in the RESIDENT.RPF. 

I understand that changing those files can be rather tedious so I have changed this from bug to enhancement. Currently looking into this.

**Comment by TrevorBarns** [comment] 2020-12-26 23:15
Fixed as of version 3.1.5-beta. 
https://github.com/TrevorBarns/luxart-vehicle-control-lite/releases/tag/3.0.5L

**Closed by TrevorBarns** 2020-12-26 23:15 UTC
Labels: enhancement
